spring.thymeleaf.mode=HTML

# Password hash algorithm
password.hash.code=SHA-256

# Postgres接続先設定
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/todo_app
spring.datasource.username=postgres
spring.datasource.password=01test001

# ログレベル
logging.level.sample.*=DEBUG

# MyBatis設定
mybatis.type-aliases-package=sample.common.dao.entity
mybatis.mapper-locations=classpath:sample/common/dao/mapper/*.xml

# セッション有効期限
server.servlet.session.timeout=1d

# SQL初期化
spring.sql.init.mode=always
